Dbt_DB_Project:
  outputs:
    dev:
      catalog: workspace
      host: abc.cloud.databricks.com
      http_path: /sql/1.0/warehouses/xxxx
      schema: default
      threads: 3
      token: xxxxxxxx
      type: databricks

    dev_2:
      catalog: workspace
      host: abc.cloud.databricks.com
      http_path: /sql/1.0/warehouses/xxxx
      schema: scd_incremental
      threads: 3
      token: xxxxxxxx
      type: databricks

    dev_3:
      catalog: workspace
      host: abc.cloud.databricks.com
      http_path: /sql/1.0/warehouses/xxxx
      schema: analytics
      threads: 3
      token: xxxxxxxx
      type: databricks
    
  target: dev
